
accueil_utilisateur:
    resource: "@AccueilBundle/Resources/config/routing/utilisateur.yml"
    prefix:   /utilisateur

accueil_projet:
    resource: "@AccueilBundle/Resources/config/routing/projet.yml"
    prefix:   /projet

accueil_category:
    resource: "@AccueilBundle/Resources/config/routing/category.yml"
    prefix:   /categorie

accueil_homepage:
    path:     /
    defaults: { _controller: AccueilBundle:Default:index }

fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
   resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
   prefix: /profile

fos_user_register:
   resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
   prefix: /register

fos_user_resetting:
   resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
   prefix: /resetting

fos_user_change_password:
   resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
   prefix: /profile
