services:
  # [...] Vos autres services
  redirect.after.login:
    class: AccueilBundle\Redirection\AfterLoginRedirection
    arguments: [@router]

  redirect.after.logout:
    class: AccueilBundle\Deconnexion\AfterLagoutRedirection
    arguments: [@router, @security.context]