administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /admin

accueil:
    resource: "@AccueilBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
