administration_homepage:
    path:     /admin
    defaults: { _controller: AdministrationBundle:Default:index }
administration_affiche:
    path:     /projet/{id}
    defaults: { _controller: AdministrationBundle:Default:afficherprojet }
administration_validation:
    path:     /validation/{id}
    defaults: { _controller: AdministrationBundle:Default:validation }
